### ISSUE TITLE
Three hours of data missing from the day's report

### ISSUE THREAD

**Issue by kristjanmar** [plausible/analytics#1976] opened 2022-06-27 03:45 UTC
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

My daily data for Sunday 26-Jun-2022 is missing three hours of data between 4-8 pm. I have several uptime checkers and they do not report the site going down for more than a few minutes last night, so this is has to be an issue with Plausible.

I also don't see an unusual amount of error reports from my Plausible proxy config in Vercel that could explain such a huge drop (thousands of visits missing). I do have a few of these though:

```
502 [stockanalysis.com/stats/api/event/](http://stockanalysis.com/stats/api/event/)
DNS_HOSTNAME_RESOLVE_FAILED: An error occurred with this application.
```

### Expected behavior

This should not happen.

### Screenshots

![CleanShot 2022-06-27 at 10 40 26](https://user-images.githubusercontent.com/22234692/175855736-b882f81f-992e-4be8-97b6-7f2d9bce7657.png)

You can see that the chart goes to near-zero for one hour and absolute zero for two hours.

### Environment

```markdown
- OS: Mac OS
- Browser: Chrome, latest
```

**Comment by kristjanmar** [comment] 2022-06-27 04:42
Also, the numbers in the report don't match. The overview page for example shows Google traffic at 6.2K, but when I click to filter "Source is Google" then it shows 5.2K. The other sources are also wrong.

![CleanShot 2022-06-27 at 11 38 46](https://user-images.githubusercontent.com/22234692/175861438-aed6cf69-9961-408b-8ba7-4a0218e96532.png)

![CleanShot 2022-06-27 at 11 40 02](https://user-images.githubusercontent.com/22234692/175861450-24ea0911-8c50-4a40-b5d4-e9f907a735a8.png)

**Comment by metmarkosaric** [comment] 2022-06-27 04:55
thanks for reporting this @kristjanmar and sorry for the inconvenience! our developers are looking into what happened and will share more as soon as possible.

**Comment by ukutaht** [comment] 2022-06-27 08:52
Yes this issue was caused by our Clickhouse database being overloaded with INSERT statements for a few hours. I suspect it has to do with imports from google analytics.

Our monitoring failed to catch the issue. We're working to improve our monitoring so we can get alerted and fix issues like this quicker.

The inconsistency in Top Sources is caused by the database being down. Since our data is denormalized for faster querying, there can be errors during incidents. We could calculate everything from scratch every time but that would be much more expensive for CPU/RAM.

Currently the system is stable so I will close this issue. We're sorry about the incident and we're doing what we can to avoid issues like this in the future.

**Comment by vinodbollini** [comment] 2022-06-27 09:56
@ukutaht will the traffic data from that period be lost? Or will it be accessible after all your database INSERTs/WRITEs have synced?
We have a couple of customers who claimed that the site was down, unfortunately at the same time as this. Wanted to compare traffic to see if there was any actual drop.

**Comment by ukutaht** [comment] 2022-06-27 14:56
The writes from that period are gone. Unfortunately we cannot keep logs so we cannot restore it either.

We'll learn from this and make our systems more reliable. I'm sorry that the data was lost this time :(

**Comment by kristjanmar** [comment] 2022-06-28 11:33
Looks like it's down again, both the dashboard and the tracking. I really like Plausible but frequent outages like this are going to be a deal breaker for me, unfortunately.

```
503 Service Unavailable
No server is available to handle this request.
```

**Comment by metmarkosaric** [comment] 2022-06-28 13:29
sorry about that @kristjanmar! this is still related to the GA imports. it's a relatively new feature so we haven't encountered these issues before. everything is back running fine again. and again, sorry about the incident. we're doing what we can to avoid issues like this in the future!

**Closed** 2022-07-10 04:32 UTC
