### ISSUE TITLE
Advanced view for aggregated data for a specific sub-path etc

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#396] opened 2020-11-05 14:33 UTC
"Is it possible to look at aggregated data for a specific sub-path? Something like /blog/*?"

(feedback via email)

Something like the "advanced" view in GA could be cool:

![Screenshot from 2020-11-05 15-28-23](https://user-images.githubusercontent.com/34340819/98253976-00842c80-1f7c-11eb-85bc-074c94000855.png)

**Comment by ukutaht** [comment] 2020-11-06 08:15
Possibly duplicate of #136

**Closed** 2020-11-06 08:29 UTC
Labels: feature request
