### ISSUE TITLE
"DETAILS" links are semi- or invisible

### ISSUE THREAD

**Issue by gravelld** [plausible/analytics#3347] opened 2023-09-15 15:24 UTC
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

The DETAILS link that should appear under _Top Sources_ is not visible and pushed beneath the _Locations_ card.

The DETAILS link for _Entry Pages_ is semi visible.

### Expected behavior

DETAILS links are fully visible and can be clicked.

### Screenshots

![Screenshot_2023-09-15_16-22-42](https://github.com/plausible/analytics/assets/873704/7504d0ac-dbea-4f2e-b06a-7e50af6862f5)
![Screenshot_2023-09-15_16-22-56](https://github.com/plausible/analytics/assets/873704/fb2af21c-a835-4cc6-8d79-c9bedf53507e)

### Environment

```markdown
- OS: Xubuntu 22.04
- Browser: Firefox
- Browser Version: 116.0.3
```

**Comment by metmarkosaric** [comment] 2023-09-15 16:03
Thanks for reporting @gravelld ! I'm not able to reproduce this. Could it be that you have some custom settings for fonts or font size in your browser?

**Comment by metmarkosaric** [comment] 2023-09-18 07:56
closing this for now but feel free to respond back and share more details if this happens on a default browser too without any customization done to the fonts. thanks!

**Closed by metmarkosaric** 2023-09-18 07:56 UTC

**Comment by gravelld** [comment] 2023-09-18 09:49
tbh this sounds plausible but I haven't knowingly edited this. I have _Allow pages to choose their own fonts, instead of your selections above_ selected in Firefox. It looks like `ui-sans-serif` is being chosen as the font. That maps to FreeSans on my system. Changing it to DejaVu Sans doesn't appear to make any difference...

**Comment by metmarkosaric** [comment] 2023-09-18 09:58
hmm weird. this looks to be the default on my machine and the dashboard looks all fine:

<img width="644" alt="Screenshot 2023-09-18 at 11 57 11" src="https://github.com/plausible/analytics/assets/34340819/33c90146-7998-4c3f-b662-193b381d8e3d">


but if i change the font size above to say 13 and refresh the dashboard, i get something that looks like the screenshots you sent

**Comment by gravelld** [comment] 2023-09-19 12:19
Fine - thanks. Definitely keep this closed - I'm sure there's some issue on my machine. I run multiple monitors with multiple resolutions and at some point I've probably changed something...
