### ISSUE TITLE
Data Outside Containers

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#124] opened 2020-06-19 10:47 UTC
"The containers have height in px. For people who’ve set a non-default font size in their browser, this pushes data outside the container. Removing the height elements, using em/rem, or using height: auto will fix this."

([imported from the old roadmap](https://plausible.nolt.io/74))

**Comment by bradonomics** [comment] 2020-08-09 16:51
Using `height: auto` on the `stats-item` elements will not fix this. The More button, being absolutely positioned, will block the last element in the list from being clicked. The pixel heights do need to be removed, but the `absolute` declarations on the More buttons need removing also.

**Comment by ukutaht** [comment] 2021-09-21 08:03
I cannot reproduce after the mobile fixes by @hirusi. Can anyone else or should this be closed?

**Comment by mwild1** [comment] 2021-09-21 08:04
Are they in a release? This issue has been annoying me for some time, so I'm happy to test :)

**Comment by metmarkosaric** [comment] 2021-09-21 08:06
you can test it on https://plausible.io/plausible.io

**Comment by mwild1** [comment] 2021-09-21 08:09
I'm afraid it still overflows the box:

![](https://matthewwild.co.uk/uploads/screenshot-20210921-1632211647-26763.png)

Firefox 91.0.2 on Ubuntu.

**Comment by ukutaht** [comment] 2021-09-21 08:31
ah gotcha, managed to reproduce

**Comment by hirusi** [comment] 2021-09-21 11:33
Let me know if I can help please. :)

**Comment by ukutaht** [comment] 2021-09-22 10:32
Fixed in https://github.com/plausible/analytics/commit/7d67f53ae0ed3f5a10986f12719bdb3849d02c36

@mwild1 Can you confirm it's working OK on staging.plausible.io/plausible.io ?

**Comment by ukutaht** [comment] 2021-09-22 10:33
@hirusi Thanks for offering to help but I already managed to knock this out. Needed `rem` heights instead of `px` on the containers.

**Comment by mwild1** [comment] 2021-09-22 10:45
@ukutaht it's looking beautiful! Thanks so much :)

**Closed** 2021-09-22 17:58 UTC
