### ISSUE TITLE
UI doesn't look right on Linux

### ISSUE THREAD

**Issue by thevladiator** [plausible/analytics#455] opened 2020-12-09 22:21 UTC
When viewing the dashboard on Linux/Google Chrome Version 87.0.4280.88 (Official Build) (64-bit) I see the widgets not correctly containing the data.
The Visitors graph goes under the containing box just like Top Pages and Top Sources.
![plausible](https://user-images.githubusercontent.com/16388609/101695682-d4037a80-3a29-11eb-8f85-6c7b3e21ad9f.png)

**Comment by ukutaht** [comment] 2020-12-10 07:50
Thanks for reporting. I'm pretty sure this is a duplicate of  #124. Do you have a non-default font-size or scaling factor?

**Comment by thevladiator** [comment] 2020-12-10 16:27
Yes...it is the same issue as #124 ...I do have a Large font set on my Google Chrome browser, instead of the default Medium.

**Comment by metmarkosaric** [comment] 2020-12-10 17:31
Thanks for the update @thevladiator! I'll close this one.

**Closed by metmarkosaric** 2020-12-10 17:31 UTC
