### ISSUE TITLE
Spaces in tracking parameters not displayed properly

### ISSUE THREAD

**Issue by corbindavenport** [plausible/analytics#229] opened 2020-07-17 14:45 UTC
**Describe the bug**
Spaces in utm tracking parameters are not displayed as spaces. Other characters might be broken as well. This is the sample URL I was testing with:
```
https://edit.photostack.app/?utm_source=Android%20App
```

**Expected behavior**
Google Analytics converts `%20` to a space when displaying information.

**Screenshots (If applicable)**

![image](https://user-images.githubusercontent.com/3879063/87798387-f1853d00-c819-11ea-9d8c-25d4b5628f47.png)

**Environment (If applicable):**
 - OS: Linux
 - Browser: Firefox
 - Version 77

**Comment by fabianfett** [comment] 2020-08-06 07:05
I can see this problem as well. Though not for spaces but for pluses “%2B”. 

Further it would be great if the source for “hello%2Bworld” could be merged with “hello+world” in the dashboard.

**Comment by nsitti** [comment] 2020-08-07 10:43
Ok

Le jeu. 6 août 2020 à 08:05, Fabian Fett <notifications@github.com> a
écrit :

**Closed** 2020-08-19 12:02 UTC
Labels: bug

**Comment by ukutaht** [comment] 2020-08-20 07:17
@corbindavenport @fabianfett I have now deployed a fix to the live site. Can you confirm the issue is resolved on your side?

**Comment by fabianfett** [comment] 2020-08-20 08:54
@ukutaht Works for me. Thanks so much for fixing this!
