### ISSUE TITLE
Plausible doesn't report data in Capacitor app

### ISSUE THREAD

**Issue by riderx** [plausible/analytics#1124] opened 2021-06-12 12:14 UTC
As speek here https://github.com/plausible/analytics/discussions/445 some of us need plausible in hybrids apps.

Plausible is awesome tool, I don't want to use other poorly privacy tools in my app, I need simple analytics in them

## Bug report
**Describe the bug**
When in capacitor or cordova app reporting should work, or a least we need a way to allow us to make it work 
`Ignoring Event: localhost`

**Environment (If applicable):**
 - OS: IOS 14
 - Browser Capacitor 
 - Version 3

**Comment by metmarkosaric** [comment] 2021-06-12 12:32
Thanks @riderx. We keep issues to actual bugs only. We've intentionally disabled localhost as most people don't want their localhost traffic counted. I will close this as it's a duplicate of #445. I cannot make any promises on the timeline of this. We are a small team with limited development resources so need to focus on most frequently requested features first.

**Closed by metmarkosaric** 2021-06-12 12:32 UTC

**Comment by riderx** [comment] 2021-06-12 23:29
Thanks @metmarkosaric, I understand, I can try to do a PR so :)

**Comment by riderx** [comment] 2021-06-13 01:00
Here you go ! https://github.com/plausible/analytics/pull/1125
