### ISSUE TITLE
[self-host] no geoip data

### ISSUE THREAD

**Issue by scambier** [plausible/analytics#1625] opened 2022-01-21 20:42 UTC
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

Edit: just to be clear: I'm _not_ asking support here, I'm reporting what looks to be an issue with the docker image.

### Describe the bug

Hello :)

I installed Plausible a few days ago on my VPS with Docker, following [these instructions](https://plausible.io/docs/self-hosting). Everything works _except_ the geoip. I have 0 stat, 0 listed country.

Looking at the docs it seems that I can use another provider for geoip resolution, but to my understanding, it should work out of the box. Anyway, I cleaned up my docker containers with `docker volume prune`, and to my surprise it deleted the volume `plausible_geoip`. So it wasn't used at all, and it expains the lack of stats.

### Expected behavior

The geoip container should be mounted and running to collect stats.

### Environment

```markdown
- OS: Debian 10 (buster), with the official Docker image
- Browser: n/a
- Browser Version: n/a
```

**Comment by ukutaht** [comment] 2022-01-21 20:55
I've triaged and tested this multiple times, each time reaching the conclusion that the docker image is working as advertised. Mostly it's caused by a reverse proxy or CDN configuration error. Are you running something in front of Plausible and are you sure it handles the `X-Forwarded-For` correctly?

I just tested `v1.4.4` again and the geolocation feature works fine so I'll close this for now.

**Closed by ukutaht** 2022-01-21 20:55 UTC

**Comment by scambier** [comment] 2022-01-22 18:57
Here is the nginx site config:

```
server {
        server_name mysite.com;
        location / {
                proxy_pass http://127.0.0.1:8352;
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mysite.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name mysite.com;
    listen 80;
    listen [::]:80;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    return 404; # managed by Certbot
}
```

Are there logs somewhere that might indicate an issue with the geoip?

**Comment by scambier** [comment] 2022-01-26 10:01
Here's my config:

```
server {
        server_name mysite.com;
        location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://localhost:8352;
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mysite.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        server_name mysite.com;
        listen 80;
        return 404; # managed by Certbot
}
```

It _looks_ ok to me, so I'm not sure what's wrong :/

**Comment by ukutaht** [comment] 2022-01-26 16:36
That looks correct to me as well. I'm not sure what the problem is. You can troubleshoot by sending dummy events directly to your Plausible docker image to see if the problem is with Plausible or not.

```bash
$ curl 'http://localhost:8352/api/event' -H 'X-Forwarded-For: 201.207.52.135' --data-binary '{"n":"pageview","u":"http://mysite.com","d":"mysite.com","r":null,"w":1666}'

```

You can use that IP address to test. The event should be stored with `CR` country code.

**Comment by scambier** [comment] 2022-01-31 07:42
Plausible correctly logs the curl visit, but still no country code. I think I'll do a backup and reinstall it from scratch when I have time, I'll keep you updated. Thanks for your help 👍

**Comment by ukutaht** [comment] 2022-01-31 16:28
Thanks

**Comment by ukutaht** [comment] 2022-02-17 15:57
> It works normally when I use the javascript embed.

What do you mean by that?

**Comment by L0g4n** [comment] 2022-05-21 15:17
I'm sorry, but the integrated GeoIP collection with `dbip` ain't working for me either, out of the box.
I'm using caddy as a reverse proxy in front of plausible, all with rootless podman containers.
This is my `Caddyfile`:
```
subdomain.domain.tld {
	uri replace /js/stats.js /js/plausible.js
	reverse_proxy 0.0.0.0:1024
	encode zstd gzip
}
```
This is the command I use to start the analytics server in the pod:
```sh
# plausible
podman run \
	-u 0:0 \
	-d --pod "$POD_NAME" \
	-e ADMIN_USER_EMAIL="$ADMIN_USER_EMAIL" \
	-e ADMIN_USER_NAME="$ADMIN_USER_NAME" \
	-e ADMIN_USER_PWD="$ADMIN_USER_PWD" \
	-e BASE_URL="$BASE_URL" \
	-e SECRET_KEY_BASE="$SECRET_KEY" \
	-e DATABASE_URL="REDACTED" \
	-e CLICKHOUSE_DATABASE_URL="http://localhost:8123/plausible_dev" \
	-e DISABLE_REGISTRATION=true \
	-e MAILER_EMAIL="REDACTED" \
	-e SMTP_HOST_ADDR="REDACTED" \
	-e SMTP_HOST_PORT="465" \
	-e SMTP_USER_NAME="noreply@l0g4n.me" \
	-e SMTP_USER_PWD="REDACTED" \
	-e SMTP_HOST_SSL_ENABLED="true" \
	--name "plausible" "$PLAUSIBLE_IMG" \
	sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
```
My understand is that the default configuration should still show the geolocation data in the dashboard, however no such data is available at all or not displayed at all.

**Comment by L0g4n** [comment] 2022-05-25 10:13
Bump at @ukutaht. Or is the integrated geoip collection broken and only MaxMind works?

**Comment by ukutaht** [comment] 2022-05-26 07:24
See previous comment. I haven't managed to reproduce so far.

> I've triaged and tested this multiple times, each time reaching the conclusion that the docker image is working as advertised. Mostly it's caused by a reverse proxy or CDN configuration error. Are you running something in front of Plausible and are you sure it handles the `X-Forwarded-For` header correctly?
> 
> I just tested `v1.4.4` again and the geolocation feature works fine so I'll close this for now.

**Comment by L0g4n** [comment] 2022-05-26 09:06
@ukutaht I found the problem:
See: https://github.com/plausible/analytics/discussions/1924
