### ISSUE TITLE
Difference between 'filter page' vs 'goal pageview'

### ISSUE THREAD

**Issue by julestran** [plausible/analytics#1843] opened 2022-04-20 12:51 UTC
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

On my self-hosted version of Plausible, I want to see stats (pageviews, visitors, etc) on a specific URL.

I created a pageview goal with that URL and I got : 
108 unique conversions
409 total conversions

and with the page filter with the same URL
8 unique visitors
11 pageviews

I attached captures if needed.

### Expected behavior

Shouldn't I have the same numbers ?

Is pageview goal working on the self-hosting version ?

### Screenshots

Filter 'page is' 
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/82525840/163955898-e135e09d-dd66-49f4-a607-1ad0517c3e0b.png">

Filter 'goal pageview'
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/82525840/163956043-8e3a39f2-1aa5-458e-ab1c-93a056df603b.png">

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by ukutaht** [comment] 2022-04-20 14:28
Hey,

This certainly looks unexpected. Do you remember when you installed Plausible? Glob-based pageview goals were added in 1.3 released last year.

**Comment by julestran** [comment] 2022-04-20 14:40
hi, we are on the 1.4.4 version.
we installed Plausible in February.

**Comment by metmarkosaric** [comment] 2022-05-09 09:24
i cannot replicate this issue unfortunately. seems to be working all fine on the cloud version. @ukutaht can perhaps share more info on what you can do

**Comment by ruslandoga** [comment] 2022-12-16 08:12
@julestran 👋

I wonder if you could check if it's still reproducible in [`v1.5.1`?](https://github.com/plausible/analytics/discussions/2507)

**Comment by metmarkosaric** [comment] 2023-01-19 07:41
i'll close this for now as we cannot reproduce it neither in cloud nor in self hosted. we can always reopen if we get more info

**Closed by metmarkosaric** 2023-01-19 07:41 UTC
Labels: self-hosting
