### ISSUE TITLE
Unique constraint error when adding a site for the first time

### ISSUE THREAD

**Issue by RobertJoonas** [plausible/analytics#2262] opened 2022-09-23 06:37 UTC
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

We've had two reports of getting the "domain is already taken" message upon adding a new site that didn't exist in our database before.

A report of what happened from one customer:

1. Tried to add a new site that didn't exist in Plausible before
2. Got the error "This domain has already been taken"
3. Reloaded the page
4. Site was added successfully and they could proceed to the next step ("Add snippet")

Unique constraint errors are common when two concurrent requests are fired. So the issue is likely in making two POST requests to `https://plausible.io/sites` when entering the domain name and clicking "Add snippet".

### Expected behavior

Should not get the unique constraint error when there is no existing site with the same name.

### Environment

```markdown
- OS: macOS 12 Monterey
- Browser: Brave
```

**Comment by ukutaht** [comment] 2022-09-23 07:46
Can you reproduce this reliably?

**Comment by RobertJoonas** [comment] 2022-09-23 07:49
Unfortunately not. BrowserStack live doesn't have the Brave browser option on macOS Monterey.

**Comment by metmarkosaric** [comment] 2022-10-03 20:48
hasn't been reported again since those two reports on the same day so i think it's safe to close this as we cannot reproduce it either

**Closed** 2022-10-04 08:27 UTC
