### ISSUE TITLE
Related Goals/Pie Charts

### ISSUE THREAD

**Issue by danrabbit** [plausible/analytics#184] opened 2020-06-25 01:11 UTC
Several of the goals we’ve configured are related options and we’d like to track which of those options users choose.

Showing all of our goals together as a bar graph makes it difficult to compare these related goals. For exclusive options, a pie chart makes more sense

For example we have goals configured for:
* HTTP vs Magnet download
* Which of 4 CDN locations were used
* The operating system used to download
* How far a user got through the payment process (Skipped, Completed, Failed)

**Comment by cassidyjames** [comment] 2020-06-25 01:53
(may be related to/duplicate of plausible/analytics#134)

**Comment by metmarkosaric** [comment] 2020-06-25 16:10
Thanks for the feedback! #171 may be related too. We're looking to make a nicer funnel visualization for things such as how many of visitors viewed a registration page and how many completed a registration (kind of like one of your examples).

**Comment by metmarkosaric** [comment] 2020-07-08 15:43
I've now added more details in #134 so let's take this topic to that thread from now and I'll close this one. Let me know if the proposed solution for categorizing/grouping related goals works for your usecases or if you see it working other way. It's early stage now so everything is possible.

The funnel visualization for multi step goals (Skipped, Completed, Failed) is a topic for #171.

Thanks!

**Closed by metmarkosaric** 2020-07-08 15:43 UTC
Labels: feature request
