### ISSUE TITLE
Compatibity with Clickhouse 24.2

### ISSUE THREAD

**Issue by luizkowalski** [plausible/analytics#3855] opened 2024-03-02 14:16 UTC
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

hey 👋🏻 

I tried to upgrade my self-hosted instance of Clickhouse, and it looks like Plausible is not yet ready for it

This is the exception I'm seeing on the console:

```
2024-03-02T14:13:30.904571761Z 14:13:30.901 request_id=F7j4ERc_wsg38ZcAAAfC [info] Sent 500 in 26ms
2024-03-02T14:13:30.904574245Z 14:13:30.901 [error] #PID<0.3764.0> running PlausibleWeb.Endpoint (connection #PID<0.3762.0>, stream id 2) terminated
2024-03-02T14:13:30.904577021Z Server: plausible.sumiu.link:80 (http)
2024-03-02T14:13:30.904579085Z Request: GET /api/stats/luizkowalski.net/countries?period=day&date=2024-03-02&filters=%7B%7D&with_imported=true&limit=300
2024-03-02T14:13:30.904581489Z ** (exit) an exception was raised:
2024-03-02T14:13:30.904583634Z     ** (Ch.Error) Code: 10. DB::Exception: Not found column _sample_factor:  in block start DateTime UInt32(size = 0), country_code LowCardinality(FixedString(2)) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, FixedString(size = 1))), site_id UInt64 UInt64(size = 0), user_id UInt64 UInt64(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.2.1.2248 (official build))
2024-03-02T14:13:30.904586258Z
2024-03-02T14:13:30.904588212Z         (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
2024-03-02T14:13:30.904596768Z         (ecto_ch 0.1.9) lib/ecto/adapters/clickhouse.ex:269: Ecto.Adapters.ClickHouse.execute/5
2024-03-02T14:13:30.904599112Z         (ecto 3.9.5) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
2024-03-02T14:13:30.904601216Z         (ecto 3.9.5) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
2024-03-02T14:13:30.904603290Z         (plausible 0.0.1) lib/plausible/stats/breakdown.ex:195: Plausible.Stats.Breakdown.breakdown_sessions/5
2024-03-02T14:13:30.904605484Z         (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:810: PlausibleWeb.Api.StatsController.countries/2
2024-03-02T14:13:30.904608129Z         (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.action/2
2024-03-02T14:13:30.904610343Z         (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.phoenix_controller_pipeline/2
2024-03-02T14:13:30.904612648Z 14:13:30.903 [debug] QUERY ERROR source="events_v2" db=21.5ms queue=0.1ms idle=1749.0ms
2024-03-02T14:13:30.904614852Z SELECT toStartOfHour(toTimeZone(e0."timestamp", {$0:String})),toUInt64(round(uniq(e0."user_id") * any(_sample_factor))) FROM "events_v2" AS e0 sample 20000000 WHERE (e0."site_id" = {$1:Int64}) AND ((e0."timestamp" >= {$2:DateTime}) AND (e0."timestamp" < {$3:DateTime})) GROUP BY toStartOfHour(toTimeZone(e0."timestamp", {$4:String})) ORDER BY toStartOfHour(toTimeZone(e0."timestamp", {$5:String})) ["Europe/Berlin", 2, ~U[2024-03-01 23:00:00Z], ~U[2024-03-02 23:00:00Z], "Europe/Berlin", "Europe/Berlin"]
```

### Expected behavior

Compatible with [CH changes](https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#-clickhouse-release-242-2024-02-29)

### Environment

```markdown
- OS: Ubuntu 22.04 (Docker)
- Browser: - 
- Browser Version: -
```

Deployment configuration (I'm using [Kamal](https://kamal-deploy.org/))

```yaml
plausible:
    image: plausible/analytics:v2.0.0
    roles:
      - web
    env:
      clear:
        BASE_URL: https://plausible.sumiu.link/
        SECRET_KEY_BASE: <%= ENV["PLAUSIBLE_SECRE_KEY_BASE"] %>
        DATABASE_URL: <%= ENV["PLAUSIBLE_DATABASE_URL"] %>
        CLICKHOUSE_DATABASE_URL: http://10.0.0.3:8123/plausible_events
        DISABLE_REGISTRATION: invite_only
        LOG_LEVEL: debug
        MAILER_ADAPTER: Bamboo.PostmarkAdapter
        MAILER_EMAIL: xxx
        MAILER_NAME: Luiz from Sumiu
      secret:
        - POSTMARK_API_KEY
    cmd: sh -c "sleep 5 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    labels:
      traefik.enable: true

  clickhouse:
    hosts:
      - accessories
    image: clickhouse/clickhouse-server:24.2
    port: 8123
    directories:
      - event-data:/var/lib/clickhouse
```

**Comment by ruslandoga** [comment] 2024-03-02 14:32
👋 @luizkowalski 

Can you please run show create on events_v2 and sessions_v2 tables? I'll try out ClickHouse 24.2 on my instance later today.

**Comment by luizkowalski** [comment] 2024-03-02 14:35
sure, but how do I do that? Plausible's app console? I'm not very familiar with all this, it is my first time playing around with self-hosting

**Comment by ruslandoga** [comment] 2024-03-02 16:34
Thank you! I've been able to reproduce it but I'm not sure what's the cause yet. `_sample_factor` is still available in ClickHouse 24.2:

```sql
7eeb32dddd7a :) select sum(s.pageviews * s._sample_factor) from sessions_v2 s sample 100;

--┌─sum(multiply(pageviews, _sample_factor))─┐
-- │                       390594.55999999976 │
-- └──────────────────────────────────────────┘

-- 1 row in set. Elapsed: 0.006 sec. Processed 20.73 thousand rows, 248.77 KB (3.22 million rows/s., 38.60 MB/s.)
-- Peak memory usage: 0.00 B.

7eeb32dddd7a :) select version();

-- ┌─version()───┐
-- │ 24.2.1.2248 │
-- └─────────────┘
```

If the fix would require changing the queries, it'd be unlikely to be merged until Plausible Cloud switches to the version requiring it.

**Comment by ruslandoga** [comment] 2024-03-02 16:42
Hm, this query seems to work in `clickhouse client`

```sql
SELECT
    toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')),
    toUInt64(round(uniq(e0.user_id) * any(_sample_factor)))
FROM events_v2 AS e0
SAMPLE 20000000
GROUP BY toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin'))
ORDER BY toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')) ASC

-- ┌─toStartOfHour(toTimeZone(timestamp, 'Europe/Berlin'))─┬─toUInt64(round(multiply(uniq(user_id), any(_sample_factor))))─┐
-- │                                   2022-08-10 17:00:00 │                                                             1 │
-- │                                   2022-08-10 18:00:00 │                                                             1 │
-- │                                   2022-08-11 11:00:00 │                                                             1 │
-- │                                   2022-08-11 12:00:00 │                                                             1 │
-- etc.

-- 981 rows in set. Elapsed: 0.039 sec. Processed 599.36 thousand rows, 7.19 MB (15.34 million rows/s., 184.13 MB/s.)
```
but adding a `WHERE` clause makes it fail
```sql
SELECT
    toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')),
    toUInt64(round(uniq(e0.user_id) * any(_sample_factor)))
FROM events_v2 AS e0
SAMPLE 20000000
WHERE (e0.site_id = 2) AND ((e0.timestamp >= '2024-03-01 23:00:00') AND (e0.timestamp < '2024-03-02 23:00:00'))
GROUP BY toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin'))
ORDER BY toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')) ASC

-- Received exception from server (version 24.2.1):
-- Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column _sample_factor:  in block timestamp DateTime UInt32(size = 0), site_id UInt64 UInt64(size = 0), user_id UInt64 UInt64(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK)
```

**Comment by ruslandoga** [comment] 2024-03-02 16:47
Enabling experimental analyzer and removing `any` results in a more sensible error:

```sql
set allow_experimental_analyzer=1;

SELECT
    toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')),
    toUInt64(round(uniq(e0.user_id) * _sample_factor))
FROM events_v2 AS e0
SAMPLE 20000000
WHERE (e0.site_id = 2) AND ((e0.timestamp >= '2024-03-01 23:00:00') AND (e0.timestamp < '2024-03-02 23:00:00'))
GROUP BY toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin'))
ORDER BY toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')) ASC

-- Received exception from server (version 24.2.1):
-- Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column e0._sample_factor is not under aggregate function and not in GROUP BY keys. In query SELECT toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')), toUInt64(round(uniq(e0.user_id) * _sample_factor)) FROM events_v2 AS e0 SAMPLE 20000000 WHERE (e0.site_id = 2) AND ((e0.timestamp >= '2024-03-01 23:00:00') AND (e0.timestamp < '2024-03-02 23:00:00')) GROUP BY toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')) ORDER BY toStartOfHour(toTimeZone(e0.timestamp, 'Europe/Berlin')) ASC. (NOT_AN_AGGREGATE)
```

**Comment by ruslandoga** [comment] 2024-03-02 17:01
Seems to be more of a ClickHouse bug, I'll try opening an issue.

**Comment by ruslandoga** [comment] 2024-03-02 17:10
https://github.com/ClickHouse/ClickHouse/issues/60685

I'll reopen the issue if it turns out it's not a bug.

**Closed by ruslandoga** 2024-03-02 17:10 UTC

**Comment by luizkowalski** [comment] 2024-03-02 17:12
Thanks a lot, @ruslandoga! I will subscribed to that issue

**Comment by dustinmoris** [comment] 2024-03-26 17:58
FYI, I tried the workaround in the linked ClickHouse issue and it worked for me by setting `query_plan_optimize_prewhere` to `0`
