### ISSUE TITLE
Crash on startup after docker image update

### ISSUE THREAD

**Issue by MarvinJWendt** [plausible/analytics#2491] opened 2022-12-02 16:58 UTC
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Plausible crashes on startup.

I updated the image to the latest version, which was pushed about an hour ago. I cannot start my plausible instance anymore, and I get a bad gateway error:

Error:
```
analytics-plausible  | init terminating in do_boot ({,[{Elixir.Jason,decode!,2,[{_},{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]}]})
analytics-plausible  |
analytics-plausible  | Crash dump is being written to: erl_crash.dump...done
analytics-plausible  | ERROR! Config provider Config.Reader failed with:
analytics-plausible  | ** (Jason.DecodeError) unexpected byte at position 38: 0x70 ("p")
analytics-plausible  |     lib/jason.ex:92: Jason.decode!/2
analytics-plausible  |     (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
analytics-plausible  |     (stdlib 3.17.1) erl_eval.erl:446: :erl_eval.expr/5
analytics-plausible  |     (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
analytics-plausible  |     (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
analytics-plausible  |     (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
analytics-plausible  |     (elixir 1.13.4) lib/config.ex:260: Config.__eval__!/3
analytics-plausible  |     (elixir 1.13.4) lib/config/reader.ex:92: Config.Reader.read!/2
```

### Expected behavior

No crash on startup.

### Environment

```markdown
- OS: Docker
- Browser: Not relevant
- Browser Version: Not relevant
- Plausible Version: latest docker image (pushed an hour ago)
```

**Comment by MarvinJWendt** [comment] 2022-12-02 17:04
PS: Manually downgrading to `v1.4` solved the issue. But it crashes with `v1.5`.

**Comment by spuniun** [comment] 2022-12-02 18:36
Confirmed that the latest and 1.5 tags from docker hub are not working. Curious that the image size is half that of 1.4

**Comment by ruslandoga** [comment] 2022-12-03 02:14
👋

It seems to be related to https://github.com/docker/build-push-action/issues/726

**Comment by ruslandoga** [comment] 2022-12-05 16:02
I've reopened the issue to make it more visible.I'll close it again once another the container image is updated.

**Comment by sobolevdmitry** [comment] 2022-12-06 13:24
Seems to work with v1.4.4

**Comment by ruslandoga** [comment] 2022-12-07 06:39
[`v1.5.1`](https://github.com/plausible/analytics/discussions/2507) has been released with a [fix.](https://github.com/plausible/analytics/pull/2503)

**Closed by ruslandoga** 2022-12-07 06:39 UTC
