### ISSUE TITLE
event api: data-api="https://..." not working

### ISSUE THREAD

**Issue by TheTesla** [plausible/analytics#2168] opened 2022-09-03 21:52 UTC
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

```
<script async defer data-domain="pionplex.de" data-api="https://plausible.pionplex.de/api/event" src="https://plausible.pionplex.de/js/script.outbound-links.js"></script>
```
is not working it always sends the POST to https://pionplex.de/api/event instead of https://plausible.pionplex.de/api/event

If I let https:// away:
```
<script async defer data-domain="pionplex.de" data-api="plausible.pionplex.de/api/event" src="https://plausible.pionplex.de/js/script.outbound-links.js"></script>
```
it is sent to: https://plausible.pionplex.de/plausible.pionplex.de/api/event

### Expected behavior

If "https://" is mentioned in data-api, it must be sent to the absolut url - in the example: https://plausible.pionplex.de/api/event

### Environment

```markdown
- OS: Ubuntu 20.04 LTS
- Browser: Chromium
- Browser Version: 104.0.5112.101
```

**Comment by RobertJoonas** [comment] 2022-09-05 07:01
Hi @TheTesla!

> If "https://" is mentioned in data-api, it must be sent to the absolut url - in the example: https://plausible.pionplex.de/api/event

That's actually exactly what our script does. If the `data-api` attribute is present, this is what we'll do (https://github.com/plausible/analytics/blame/master/tracker/src/plausible.js):

```js
var endpoint = scriptEl.getAttribute('data-api') || defaultEndpoint(scriptEl)
```

And then:

```js
var request = new XMLHttpRequest();
request.open('POST', endpoint, true);
```

If `data-api` is present, we're using this exact attribute value to open the POST request. So I don't think this is an issue with our tracker script. Perhaps you're redirecting the requests from your subdomain? Closing this at the moment as I couldn't reproduce the issue.

**Closed by RobertJoonas** 2022-09-05 07:01 UTC

**Comment by TheTesla** [comment] 2022-09-05 07:14
Is it possible, the browser prevents it to access the URL?
