### ISSUE TITLE
[Help wanted] how to identify visitor identity

### ISSUE THREAD

**Issue by archerbj** [plausible/analytics#1140] opened 2021-06-22 07:24 UTC
Hi, Thanks for the great project first! 

I am trying to figure out how to record user actions on my website. And the customized event + goal can do the work.

But from the docs, customized event should not carry any personal identity information like username.

> Note that you must ensure that no personally identifiable information (PII) is sent to Plausible Analytics with custom properties. PII is information that could be used on its own to identify, contact, or precisely locate an individual.

If this is the rule, how can I know which user made the action?  
Any may I ask why PII shouldn't be sent to Plausible Analytics ?

**Comment by metmarkosaric** [comment] 2021-06-22 07:26
closing as it's duplicate of https://github.com/plausible/analytics/discussions/1141

**Closed by metmarkosaric** 2021-06-22 07:26 UTC
